spring.application.name=LoyaltySvc
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/loyalty_svc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Test1234
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false